services:

  project-onyx-backend-api:
    build:
      context: .
      args:
        APP_VERSION: ${APP_VERSION:-1.0.0}
    image: project-onyx-backend-api:${APP_VERSION:-1.0.0}
    container_name: project-onyx-backend-api-${APP_VERSION:-1.0.0}
    restart: unless-stopped
    ports:
      - "${PORT:-2805}:2805"
    env_file: .env
    networks:
      - backend_network

networks:
  backend_network:
    name: "onyx_network"
    external: true
