'use strict';

const OPERATION_SECTIONS = [
  'AUTHENTICATION', 'AUTHORIZATION', 'USER_MANAGEMENT',
  'OTP_OPERATIONS', 'NOTIFICATION', 'SYSTEM_SETTINGS',
  'FILE_UPLOAD', 'DATABASE_OPERATIONS', 'API_ACCESS',
  'SECURITY', 'ADMIN_OPERATIONS',
  'STUDENT_OPERATIONS', 'ACADEMICIAN_OPERATIONS',
  'ROLL_CALL', 'LECTURE_MANAGEMENT',
  'UNIVERSITY_MANAGEMENT', 'DEPARTMENT_MANAGEMENT',
  'FACULTY_MANAGEMENT', 'CLASSROOM_MANAGEMENT', 'BUILDING_MANAGEMENT',
  'SUPPORT_TICKET', 'AUDIT_LOG', 'SYSTEM_HEALTH',
  'BACKUP_RESTORE', 'DATA_EXPORT', 'DATA_IMPORT',
];

module.exports = {
  'audit.operationSections': OPERATION_SECTIONS,
};
