'use strict';

const OPERATION_TYPES = [
  'CREATE', 'READ', 'UPDATE', 'DELETE',
  'LOGIN', 'LOGOUT', 'REGISTER',
  'PASSWORD_RESET', 'PASSWORD_CHANGE',
  'EMAIL_VERIFICATION', 'PHONE_VERIFICATION',
  'OTP_SEND', 'OTP_VERIFY', 'OTP_RESEND',
  'FILE_UPLOAD', 'FILE_DOWNLOAD', 'FILE_DELETE',
  'EXPORT', 'IMPORT', 'BACKUP', 'RESTORE',
  'CONFIGURATION_CHANGE', 'PERMISSION_CHANGE', 'ROLE_ASSIGNMENT',
  'ACCESS_GRANTED', 'ACCESS_DENIED',
  'SUSPICIOUS_ACTIVITY', 'SECURITY_ALERT',
  'SYSTEM_ERROR', 'MAINTENANCE', 'HEALTH_CHECK',
  'API_CALL', 'DATABASE_QUERY', 'CACHE_OPERATION',
  'NOTIFICATION_SEND', 'EMAIL_SEND', 'SMS_SEND', 'PUSH_NOTIFICATION',
  'ROLL_CALL_START', 'ROLL_CALL_END', 'ROLL_CALL_SIGNATURE',
  'LECTURE_SCHEDULE', 'ATTENDANCE_MARK', 'GRADE_ASSIGNMENT',
  'SUPPORT_TICKET_CREATE', 'SUPPORT_TICKET_RESPOND', 'SUPPORT_TICKET_CLOSE',
];

module.exports = {
  'audit.operationTypes': OPERATION_TYPES,
};
